modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Cursee-Development"
logoFile="icon.png"

[[mods]]
modId="more_beautiful_torches"
version="3.0.0"
displayName="More Beautiful Torches"
displayURL="https://github.com/Cursee-Development"
authors="Lupin, Jason13, TrulySinclair"
description='''Adds tons of torches to Minecraft!'''
credits='''Credit to Jared (Bookshelf) and Serilum (Collective).'''

[[dependencies.more_beautiful_torches]]
modId="minecraft"
mandatory=true
versionRange="[1.20.6]"
ordering="NONE"
side="BOTH"

# MonoLib dependency
[[dependencies.more_beautiful_torches]]
modId="monolib"
mandatory=true
versionRange="[1.2.0,)"
ordering="NONE"
side="BOTH"